//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Investments.rc
//
#define ID_B_CALCULATE                  2
#define ID_APPLY                        3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_InvestmentsTYPE             130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_CFondoDlg                   311
#define IDD_InversionDlg                312
#define IDD_QueryInversionesDlg         313
#define IDD_RendimientoDlg              314
#define IDD_RendimientosTableDlg        315
#define IDD_GenericGrid                 316
#define IDC_RADIO1                      1000
#define IDC_E_FONDO_ID                  1001
#define IDC_E_FONDO_NAME                1002
#define IDC_RADIO2                      1003
#define IDC_E_FONDO_ABREVIACION         1004
#define IDC_LIST_FONDOS                 1005
#define IDC_E_INVERSION_ID              1006
#define ID_ERASE                        1007
#define ID_NEW                          1008
#define IDC_E_INVERSION_NUM_PARTICIPACIONES 1009
#define IDC_DT_FECHA_INVERSION          1010
#define IDC_CB_FONDOS                   1011
#define IDC_LIST_INVERSIONES            1012
#define IDC_E_RENDIMIENTO_PARTICIPACIONES 1012
#define IDC_B_FONDOS                    1013
#define IDC_B_QUERIES                   1014
#define IDC_E_RENDIMIENTO_ID            1015
#define IDC_E_RENDIMIENTO_UNITARIO      1016
#define IDC_DT_FECHA_RENDIMIENTO        1017
#define IDC_LIST_RENDIMIENTOS           1018
#define IDC_GRID_RENDIMIENTOS           1019
#define IDC_B_FILTER                    1021
#define IDC_DATETIME_INICIO             1022
#define IDC_DATETIME_FINAL              1023
#define IDC_CK_FILTER_BY_DATES          1024
#define IDC_B_FILTER_CLEAR              1025
#define IDC_B_RENDIMIENTO               1027
#define IDC_GRID_GENERIC                1028
#define ID_FILE_FONDO                   32771
#define ID_FILE_INVERSION               32772
#define ID_FILE_RENDIMIENTO             32773
#define ID_FILE_RENDIMIENTOSTABLA       32774
#define ID_FILE_GENERICGRID             32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           317
#endif
#endif
